### ISSUE TITLE
Random radio, drop down Fields are not working. Inclusion of new "decimal" field

### ISSUE THREAD

**Issue by osama3101995** [Juppie902/LinkedIn-Easy-Apply-Bot#2]
@Juppie902  Hey, great work updating the code but there seem to be issue with autoselection of questions that are random. Such as there is a decimal point question, discard is not being clicked when it cant proceed, radio buttons dont work nor drop down. I am checking the code myself but it would be great if you can take a look

**Comment by Juppie902** [comment]
Hello @osama3101995 I had the fix already contained locally for some time , I tested it and forgot to push when it was ready.
I tried to fix most things, points of pain were selectors stopped working so I had to learn what is and start using XPath.
I just pushed a few commits I was ahead with.
Please test now the issues with decimal and radio selectors, I think drop down are the easiest and were fixed, but I think radio selectors still don't work because of the function receving an object that cannot be selected (I think literal text), so I will be glad if you could help.
If this issue gets resolved let's open another one with the specific problem for easier issue tracking and maybe possibly someone from the community contributing to a fix (my python skills are like 50%)

**Comment by osama3101995** [comment]
Hey @Juppie902 Hey, yeah I was trying to resolve stuff from my side as well. I am a JS dev, not Python so I am just winging it haha. I have also added my own functionality to avoid "locations" (I ony apply to worldwide and remote options, let me know if you want to see that code). However, I just add the name of the countries that I want to avoid in the same list for blacklist companies. Anyways. I will do a pull and check if stuff works. Thanks!. I will look at the radio selector option issue as well. Maybe we can improvise it somehow. 

PS: I am not sure if you know, but checkbox for "terms and conditions" was also not working so I found a  work around for it although, it isnt great.

**Comment by osama3101995** [comment]
Update: Sorry, I am very new to this. Kindly check my fork for changes. Not sure how I can commit to your branch without authorization. Thanks! Let me know if I can be allowed to commit.:

https://github.com/osama3101995/LinkedIn-Easy-Apply-Bot

**Comment by osama3101995** [comment]
Hey @Juppie902 , for me, the decimal and radio buttons are still not working. It would get stuck and not move forward.
